### PR TITLE
Support specified headers

### PR DESCRIPTION
**Pull request by ITJesse**

### CODE REVIEW

**Comment by marcoizzo** [comment]
Build fail here:
```
if (_onPhotoViewerError) {
   _onPhotoViewerError(nil);
}
```
Commenting works.
@alwx please merge PR :)

**Comment by drpiou** [comment]
Thanks

**Comment by alwx** [comment]
Sorry for the delay. Merged.

**Comment by levani** [comment]
I ended up pointing to specific commit that includes this PR from package.json:

> "react-native-photo-view": "git://github.com/alwx/react-native-photo-view.git#c58fd6b30d627fa23e39520d4fc3325ade8b0a51"

**Pull request merged**
